name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs: 
  cd:
    name: 🚀 Deploy to GCP (SSH)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to GCP
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_PROD_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            bash ~/start_server.sh 

      - name: ✅ Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"✅  CD 완료 브랜치: \`${{ github.ref_name }}\`\"}" \
              ${{ secrets.DISCORD_WEBHOOK }}
